### ISSUE TITLE
did not resolve pkg:golang/github.com/euank/go-kmsg-parser@v2.0.0%2Bincompatible

### ISSUE THREAD

**Issue by vchhasatia** [Xpertians/xmonkey-namonica#31]
Failed to clone repository: Command '['git', '-C', '/var/folders/wn/lyq1pt6j30qdwpsmzt5xd77c0000gr/T/tmpbqv5iaip', 'checkout', 'v2.0.0%2Bincompatible']' returned non-zero exit status 1.
Error: Command '['git', '-C', '/var/folders/wn/lyq1pt6j30qdwpsmzt5xd77c0000gr/T/tmpbqv5iaip', 'checkout', 'v2.0.0%2Bincompatible']' returned non-zero exit status 1.

**Comment by oscarvalenzuelab** [comment]
Confirmed fix offline.
